正常未作处理时, 程序遇到运行时错误(例如: 使用空指针, 类型转换出错...)时, 程序会立即退出, 但是有时不希望程序直接退出, 而是报告错误然后继续运行, 此时就涉及到异常处理了

使用 `throw new ExceptionObject(...)` 的格式抛出异常
```java
/* Associates the specified value with the specified key in this map.
   Throws an IllegalArgumentException if the key is null. */
public void add(T x) {
    if (x == null) {
        throw new IllegalArgumentException("can't add null");
    }
    if (contains(x)) {
        return;
    }
    items[size] = x;
    size += 1;
}
```